#ifndef PRG32_CONFIG_H
#define PRG32_CONFIG_H

#include "sdkconfig.h"

/* Runtime console mode. */
#define PRG32_MODE_UART_ONLY 0
#define PRG32_MODE_LCD_ONLY 1
#define PRG32_MODE_UART_LCD_MIRROR 2

#ifdef CONFIG_PRG32_DEFAULT_MODE_UART_ONLY
#define PRG32_DEFAULT_MODE PRG32_MODE_UART_ONLY
#elif defined(CONFIG_PRG32_DEFAULT_MODE_LCD_ONLY)
#define PRG32_DEFAULT_MODE PRG32_MODE_LCD_ONLY
#else
#define PRG32_DEFAULT_MODE PRG32_MODE_UART_LCD_MIRROR
#endif

#ifndef PRG32_DEBUG
#define PRG32_DEBUG CONFIG_PRG32_DEBUG
#endif

#if CONFIG_PRG32_DISPLAY_QEMU_RGB
/* QEMU screen builds do not touch physical board pins. */
#define PRG32_PIN_LCD_MOSI -1
#define PRG32_PIN_LCD_MISO -1
#define PRG32_PIN_LCD_SCLK -1
#define PRG32_PIN_LCD_CS -1
#define PRG32_PIN_LCD_DC -1
#define PRG32_PIN_LCD_RST -1
#define PRG32_PIN_LCD_BL -1

#define PRG32_LCD_SPI_CLOCK_HZ -1
#define PRG32_LCD_BACKLIGHT_ACTIVE_LEVEL -1
#define PRG32_LCD_BOOT_TEST_MS -1
#define PRG32_LCD_SOFT_SPI -1
#define PRG32_BOOT_SIGNAL_ENABLE -1
#define PRG32_BOOT_DIAGNOSTIC_DELAY_MS 0

#define PRG32_PIN_BTN_LEFT -1
#define PRG32_PIN_BTN_RIGHT -1
#define PRG32_PIN_BTN_UP -1
#define PRG32_PIN_BTN_DOWN -1
#define PRG32_PIN_BTN_A -1
#define PRG32_PIN_BTN_B -1
#define PRG32_PIN_BTN_START -1

#define PRG32_PIN_SETUP -1

#define PRG32_PIN_BUZZER -1

#define PRG32_PIN_RGB_LED -1

#define PRG32_GAME_UPLOAD_ENABLE 0

#define PRG32_WIFI_SCORES_ENABLE 0

#else /* Physical ESP32-C6 build. */

// Display ILI9341
#define PRG32_PIN_LCD_MOSI CONFIG_PRG32_PIN_LCD_MOSI
#define PRG32_PIN_LCD_MISO CONFIG_PRG32_PIN_LCD_MISO
#define PRG32_PIN_LCD_SCLK CONFIG_PRG32_PIN_LCD_SCLK
#define PRG32_PIN_LCD_CS CONFIG_PRG32_PIN_LCD_CS
#define PRG32_PIN_LCD_DC CONFIG_PRG32_PIN_LCD_DC
#define PRG32_PIN_LCD_RST CONFIG_PRG32_PIN_LCD_RST
#define PRG32_PIN_LCD_BL CONFIG_PRG32_PIN_LCD_BL

#define PRG32_LCD_SPI_CLOCK_HZ CONFIG_PRG32_LCD_SPI_CLOCK_HZ
#define PRG32_LCD_BACKLIGHT_ACTIVE_LEVEL CONFIG_PRG32_LCD_BACKLIGHT_ACTIVE_LEVEL
#define PRG32_LCD_BOOT_TEST_MS CONFIG_PRG32_LCD_BOOT_TEST_MS
#define PRG32_LCD_SOFT_SPI CONFIG_PRG32_LCD_SOFT_SPI
#define PRG32_BOOT_SIGNAL_ENABLE CONFIG_PRG32_BOOT_SIGNAL_ENABLE
#define PRG32_BOOT_DIAGNOSTIC_DELAY_MS CONFIG_PRG32_BOOT_DIAGNOSTIC_DELAY_MS

// Joystick
#define PRG32_PIN_BTN_UP CONFIG_PRG32_PIN_BTN_UP
#define PRG32_PIN_BTN_DOWN CONFIG_PRG32_PIN_BTN_DOWN
#define PRG32_PIN_BTN_LEFT CONFIG_PRG32_PIN_BTN_LEFT
#define PRG32_PIN_BTN_RIGHT CONFIG_PRG32_PIN_BTN_RIGHT
#define PRG32_PIN_BTN_START CONFIG_PRG32_PIN_BTN_START
#define PRG32_PIN_BTN_A CONFIG_PRG32_PIN_BTN_A
#define PRG32_PIN_BTN_B CONFIG_PRG32_PIN_BTN_B

/* Enter setup by holding A+B during boot; no dedicated setup GPIO is wired. */
#define PRG32_PIN_SETUP CONFIG_PRG32_PIN_SETUP

// Buzzer is deactivated
#define PRG32_PIN_BUZZER CONFIG_PRG32_PIN_BUZZER

/*
 * Many ESP32-C6 boards route the onboard addressable RGB LED to GPIO8. The
 * reference PRG32 ILI9341 harness uses GPIO1 for LCD D/C, leaving GPIO8 free.
 */
#define PRG32_PIN_RGB_LED CONFIG_PRG32_PIN_RGB_LED

/*
 * Uploadable game cartridges.
 *
 * Physical-board builds enable a small SoftAP + HTTP API by default so the
 * firmware can be flashed once and games can be replaced from a host tool.
 * QEMU builds keep Wi-Fi disabled and use python3 -m prg32 to patch the
 * emulator flash image.
 */
#ifdef CONFIG_PRG32_GAME_UPLOAD_ENABLE
#define PRG32_GAME_UPLOAD_ENABLE 1
#else
#define PRG32_GAME_UPLOAD_ENABLE 0
#endif

#endif

/* Keep examples and board documentation tied to the configured audio values. */
#define PRG32_PIN_AUDIO_BCLK CONFIG_PRG32_AUDIO_I2S_BCLK_GPIO
#define PRG32_PIN_AUDIO_LRCLK CONFIG_PRG32_AUDIO_I2S_LRCLK_GPIO
#define PRG32_PIN_AUDIO_DATA CONFIG_PRG32_AUDIO_I2S_DATA_GPIO
#define PRG32_PIN_AUDIO_SD CONFIG_PRG32_AUDIO_I2S_SD_GPIO
#define PRG32_AUDIO_SAMPLE_RATE CONFIG_PRG32_AUDIO_SAMPLE_RATE
#define PRG32_AUDIO_MAX_VOICES CONFIG_PRG32_AUDIO_MAX_VOICES
#define PRG32_AUDIO_DEFAULT_VOLUME_PCT CONFIG_PRG32_AUDIO_DEFAULT_VOLUME_PCT

/* QEMU uses UART 1 to direct audio to python listener */
#define PRG32_QEMU_UART_1_TX CONFIG_PRG32_QEMU_UART_1_TX
#define PRG32_QEMU_UART_1_RX CONFIG_PRG32_QEMU_UART_1_RX

/* Wifi Configuration */
/* Optional Wi-Fi score REST API. Fill credentials before flashing. */
#ifndef PRG32_WIFI_SCORES_ENABLE
#ifdef CONFIG_PRG32_WIFI_SCORES_ENABLE
#define PRG32_WIFI_SCORES_ENABLE 1
#else
#define PRG32_WIFI_SCORES_ENABLE 0
#endif
#endif

#define PRG32_WIFI_SSID CONFIG_PRG32_WIFI_SSID
#define PRG32_WIFI_PASSWORD CONFIG_PRG32_WIFI_PASSWORD
#define PRG32_SCORE_MAX 16
#define PRG32_IDLE_HEARTBEAT_MS 5000

/* Optional cartridge multiplayer service over Wi-Fi STA + WebSocket. */
#ifdef CONFIG_PRG32_MULTIPLAYER_ENABLE
#define PRG32_MULTIPLAYER_ENABLE 1
#else
#define PRG32_MULTIPLAYER_ENABLE 0
#endif
#define PRG32_MULTIPLAYER_SERVER_URL CONFIG_PRG32_MULTIPLAYER_SERVER_URL
#define PRG32_MULTIPLAYER_SEND_PERIOD_MS 50
#define PRG32_MULTIPLAYER_PEER_TIMEOUT_MS 3000

#if CONFIG_PRG32_DISPLAY_QEMU_RGB
#define PRG32_MULTIPLAYER_TRANSPORT_ENABLE 0
#else
#define PRG32_MULTIPLAYER_TRANSPORT_ENABLE PRG32_MULTIPLAYER_ENABLE
#endif

#define PRG32_WIFI_STA_ENABLE                                                  \
  (PRG32_WIFI_SCORES_ENABLE || PRG32_MULTIPLAYER_TRANSPORT_ENABLE || CONFIG_PRG32_WIFI_BOOT_MODE_STA)
#define PRG32_WIFI_AP_ENABLE (PRG32_GAME_UPLOAD_ENABLE || CONFIG_PRG32_WIFI_BOOT_MODE_AP)

#if CONFIG_PRG32_DISPLAY_QEMU_RGB
#define PRG32_WIFI_ENABLE 0
#else
#define PRG32_WIFI_ENABLE (PRG32_WIFI_STA_ENABLE || PRG32_WIFI_AP_ENABLE)
#endif
/* Autoload the sole/default cartridge. Hold A+B at boot to enter setup;
 * setup also opens when no unambiguous cartridge can boot. Classroom images
 * may set this to 1 to force setup on every boot. */
#define PRG32_BOOT_SETUP_MODE CONFIG_PRG32_BOOT_SETUP_MODE
#define PRG32_WIFI_AP_SSID CONFIG_PRG32_WIFI_SSID
#define PRG32_WIFI_AP_PASSWORD CONFIG_PRG32_WIFI_PASSWORD
#define PRG32_WIFI_AP_CHANNEL CONFIG_PRG32_WIFI_AP_CHANNEL
#define PRG32_WIFI_AP_MAX_CONN CONFIG_PRG32_WIFI_AP_MAX_CONN
#define PRG32_WIFI_COUNTRY_CODE CONFIG_PRG32_WIFI_COUNTRY_CODE
#define PRG32_WIFI_STA_LEGACY_PROTOCOLS CONFIG_PRG32_WIFI_STA_LEGACY_PROTOCOLS

/* CartridgeStore integration constants. */
#define PRG32_STORE_URL_MAX_LEN 128
#define PRG32_STORE_SERVER_URL CONFIG_PRG32_STORE_URL
#define PRG32_STORE_MDNS_SERVICE "_prg32store"
#define PRG32_STORE_MDNS_PROTO "_tcp"
#define PRG32_STORE_MDNS_TIMEOUT_MS 3000
#define PRG32_STORE_DEFAULT_PORT 5080
#define PRG32_STORE_CHUNK_BYTES 4096
#define PRG32_STORE_DOWNLOAD_STACK 8192
#define PRG32_STORE_HTTP_TIMEOUT_MS 5000

/*
 * SELECT is the classroom-facing name; START remains a source-compatible alias.
 * Set PRG32_ENABLE_SEPARATE_SELECT_PIN to 1 in a local build only when an
 * optional harness provides a distinct SELECT input on GPIO20.
 */
#ifndef PRG32_ENABLE_SEPARATE_SELECT_PIN
#ifdef CONFIG_PRG32_ENABLE_SEPARATE_SELECT_PIN
#define PRG32_ENABLE_SEPARATE_SELECT_PIN 1
#else
#define PRG32_ENABLE_SEPARATE_SELECT_PIN 0
#endif
#endif

#if CONFIG_PRG32_DISPLAY_QEMU_RGB
#define PRG32_PIN_BTN_SELECT PRG32_PIN_BTN_START
#elif PRG32_ENABLE_SEPARATE_SELECT_PIN
#define PRG32_PIN_BTN_SELECT 20
#else
#define PRG32_PIN_BTN_SELECT PRG32_PIN_BTN_START
#endif

#define MENU_ACCEPT (PRG32_BTN_SELECT | PRG32_BTN_A)
#define MENU_CANCEL PRG32_BTN_B

#endif
