from __future__ import annotations

import argparse
import importlib.util
import io
from pathlib import Path
import contextlib
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = ROOT / "tools" / "prg32_game.py"


def load_tool():
    spec = importlib.util.spec_from_file_location("prg32_game", TOOL_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {TOOL_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


prg32_game = load_tool()


class PartitionParsingTests(unittest.TestCase):
    def test_parse_partition_size_units(self) -> None:
        self.assertEqual(prg32_game.parse_partition_size("512K"), 512 * 1024)
        self.assertEqual(prg32_game.parse_partition_size("2M"), 2 * 1024 * 1024)
        self.assertEqual(prg32_game.parse_partition_size("0x210000"), 0x210000)

    def test_read_partition_slot(self) -> None:
        offset, size = prg32_game.read_partition_slot(
            ROOT / "partitions_prg32.csv",
            "cart0",
        )
        self.assertEqual(offset, 0x210000)
        self.assertEqual(size, 512 * 1024)


class SymbolParsingTests(unittest.TestCase):
    def test_parse_nm_ignores_non_symbol_lines(self) -> None:
        symbols = prg32_game.parse_nm(
            """
00000000 T prg32_ticks_ms
not-a-symbol
00000010 D prg32_cart_exec
"""
        )
        self.assertEqual(symbols["prg32_ticks_ms"], 0)
        self.assertEqual(symbols["prg32_cart_exec"], 0x10)

    def test_write_imports_emits_all_imports(self) -> None:
        imports = {
            name: 0x40000000 + index * 4
            for index, name in enumerate(prg32_game.IMPORT_NAMES)
        }
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "imports.ld"
            prg32_game.write_imports(path, imports)
            text = path.read_text(encoding="utf-8")

        self.assertIn("Generated by tools/prg32_game.py", text)
        self.assertIn("PROVIDE(prg32_ticks_ms = 0x40000000);", text)
        self.assertIn("PROVIDE(prg32_score_submit =", text)

    def test_imports_include_platform_tile_helpers(self) -> None:
        self.assertIn("prg32_playfield_draw_dual", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_platform_actor_step", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_platform_camera_follow", prg32_game.IMPORT_NAMES)

    def test_imports_include_audio_plus_helpers(self) -> None:
        self.assertIn("prg32_audio_play_sample_pan", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_audio_note_on_pan", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_audio_get_mode", prg32_game.IMPORT_NAMES)

    def test_imports_include_splash_helpers(self) -> None:
        self.assertIn("prg32_splash_draw", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_splash_show", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_splash_show_default", prg32_game.IMPORT_NAMES)

    def test_detect_entries_accepts_c_prefix(self) -> None:
        entries = prg32_game.detect_entries(
            {
                "platformer_c_init": 0,
                "platformer_c_update": 4,
                "platformer_c_draw": 8,
            },
            "platformer_c",
        )
        self.assertEqual(
            entries,
            ("platformer_c_init", "platformer_c_update", "platformer_c_draw"),
        )


class PortableHeaderTests(unittest.TestCase):
    def test_portable_build_uses_position_tolerant_riscv_flags(self) -> None:
        text = TOOL_PATH.read_text(encoding="utf-8")

        self.assertIn('"-mcmodel=medany"', text)
        self.assertIn('"-msmall-data-limit=0"', text)

    def test_v2_header_records_abi_table_import_model(self) -> None:
        header = prg32_game.CART_HEADER_V2.pack(
            prg32_game.CART_MAGIC,
            prg32_game.CART_ABI_MAJOR,
            prg32_game.CART_ABI_MINOR,
            prg32_game.CART_HEADER_V2.size,
            prg32_game.PRG32_CART_FLAG_ABI_TABLE,
            prg32_game.FALLBACK_CART_LOAD_ADDR,
            4,
            4,
            0,
            0,
            0,
            0,
            b"test" + b"\0" * 28,
            prg32_game.ABI_HASH,
            prg32_game.FEATURE_BITS["audio"],
            prg32_game.FEATURE_BITS["sprites"],
            0,
            0,
            0,
            prg32_game.PRG32_IMPORT_MODEL_ABI_TABLE,
        )
        with tempfile.TemporaryDirectory() as tmp:
            cart = Path(tmp) / "portable.prg32"
            cart.write_bytes(header + b"\0\0\0\0")
            buf = io.StringIO()
            args = argparse.Namespace(cartridge=str(cart))
            with contextlib.redirect_stdout(buf):
                prg32_game.inspect_metadata(args)
        text = buf.getvalue()
        self.assertIn('"import_model": "abi-table"', text)
        self.assertIn(f'"abi_hash": "0x{prg32_game.ABI_HASH:08x}"', text)


class QemuUploadTests(unittest.TestCase):
    def test_upload_qemu_stages_cartridge_at_partition_offset(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            flash = tmp_path / "qemu_flash.bin"
            cart = tmp_path / "game.prg32"
            partitions = tmp_path / "partitions.csv"

            payload = b"\0\0\0\0"
            header = prg32_game.CART_HEADER_V2.pack(
                prg32_game.CART_MAGIC,
                prg32_game.CART_ABI_MAJOR,
                prg32_game.CART_ABI_MINOR,
                prg32_game.CART_HEADER_V2.size,
                prg32_game.PRG32_CART_FLAG_ABI_TABLE,
                prg32_game.FALLBACK_CART_LOAD_ADDR,
                len(payload),
                len(payload),
                0,
                0,
                0,
                0,
                b"test" + b"\0" * 28,
                prg32_game.ABI_HASH,
                0,
                0,
                0,
                0,
                0,
                prg32_game.PRG32_IMPORT_MODEL_ABI_TABLE,
            )
            flash.write_bytes(b"\x00" * 256)
            cart.write_bytes(header + payload)
            partitions.write_text(
                "cart0, data, 0x40, 0x10, 128,\n",
                encoding="utf-8",
            )

            args = argparse.Namespace(
                flash=str(flash),
                cartridge=str(cart),
                partitions=str(partitions),
                slot="cart0",
            )
            prg32_game.upload_qemu(args)

            data = flash.read_bytes()
            self.assertEqual(data[0x10:0x14], b"PRG2")
            erased = data[0x10 + len(header) + len(payload):0x10 + 128]
            self.assertEqual(erased, b"\xff" * len(erased))


class DoctorTests(unittest.TestCase):
    def test_host_only_doctor_does_not_require_esp_idf(self) -> None:
        rc = prg32_game.main(["doctor", "--host-only"])
        self.assertEqual(rc, 0)


if __name__ == "__main__":
    unittest.main()
