#ifndef PRG32_AUDIO_CONFIG_H
#define PRG32_AUDIO_CONFIG_H

#include "sdkconfig.h"

#ifndef CONFIG_PRG32_AUDIO_ENABLED
#define CONFIG_PRG32_AUDIO_ENABLED 0
#endif

#ifndef CONFIG_PRG32_AUDIO_SAMPLE_RATE
#define CONFIG_PRG32_AUDIO_SAMPLE_RATE 22050
#endif

#ifndef CONFIG_PRG32_AUDIO_MAX_VOICES
#define CONFIG_PRG32_AUDIO_MAX_VOICES 6
#endif

#ifndef CONFIG_PRG32_AUDIO_I2S_BCLK_GPIO
#define CONFIG_PRG32_AUDIO_I2S_BCLK_GPIO 4
#endif

#ifndef CONFIG_PRG32_AUDIO_I2S_LRCLK_GPIO
#define CONFIG_PRG32_AUDIO_I2S_LRCLK_GPIO 11
#endif

#ifndef CONFIG_PRG32_AUDIO_I2S_DATA_GPIO
#define CONFIG_PRG32_AUDIO_I2S_DATA_GPIO 23
#endif

#ifndef CONFIG_PRG32_AUDIO_I2S_SD_GPIO
#define CONFIG_PRG32_AUDIO_I2S_SD_GPIO -1
#endif

#if CONFIG_PRG32_AUDIO_MODE_STEREO
#define PRG32_AUDIO_DEFAULT_MODE PRG32_AUDIO_MODE_STEREO
#else
#define PRG32_AUDIO_DEFAULT_MODE PRG32_AUDIO_MODE_MONO
#endif

#define PRG32_AUDIO_MAX_SAMPLES 64
#define PRG32_AUDIO_MAX_INSTRUMENTS 32
#define PRG32_AUDIO_MAX_TRACKS 16
#define PRG32_AUDIO_MIX_FRAMES 128
#define PRG32_AUDIO_FP_SHIFT 16
#define PRG32_AUDIO_PITCH_BASE 1024u

#endif
