#!/usr/bin/env python3
"""Generate PRG32 portable cartridge ABI files."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

from prg32.utilities.env_variables import ROOT_DIR, PRG32_ABI_JSON_PATH

ROOT = ROOT_DIR
ABI_JSON = PRG32_ABI_JSON_PATH
WARNING = "Generated by prg32; do not edit manually."

FEATURE_BITS = {
    "audio": "PRG32_FEATURE_AUDIO",
    "wifi": "PRG32_FEATURE_WIFI",
    "multiplayer": "PRG32_FEATURE_MULTIPLAYER",
    "metrics": "PRG32_FEATURE_METRICS",
    "audio_plus": "PRG32_FEATURE_AUDIO_PLUS",
    "keyboard": "PRG32_FEATURE_KEYBOARD",
    "tilemap": "PRG32_FEATURE_TILEMAP",
    "platformer": "PRG32_FEATURE_PLATFORMER",
    "sprites": "PRG32_FEATURE_SPRITES",
}


def load_abi(path: Path) -> dict:
    abi = json.loads(path.read_text(encoding="utf-8"))
    names = [fn["name"] for fn in abi["functions"]]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SystemExit("duplicate ABI function names: " + ", ".join(duplicates))
    return abi


def abi_hash(abi: dict) -> int:
    canonical = {
        "major": abi["major"],
        "minor": abi["minor"],
        "functions": [
            {
                "name": fn["name"],
                "return": fn.get("return", "void"),
                "args": fn.get("args", []),
                "feature": fn.get("feature", "core"),
            }
            for fn in abi["functions"]
        ],
    }
    blob = json.dumps(canonical, sort_keys=True, separators=(",", ":")).encode()
    return int.from_bytes(hashlib.sha256(blob).digest()[:4], "little")


def enum_name(name: str) -> str:
    return "PRG32_ABI_FN_" + name.upper()


def generated_files(abi: dict) -> dict[Path, str]:
    major = int(abi["major"])
    minor = int(abi["minor"])
    hash_value = abi_hash(abi)
    functions = abi["functions"]

    enum_lines = [
        "#pragma once",
        "",
        f"/* {WARNING} */",
        "",
        "enum {",
    ]
    for index, fn in enumerate(functions):
        enum_lines.append(f"    {enum_name(fn['name'])} = {index},")
    enum_lines.append(f"    PRG32_ABI_FN_COUNT = {len(functions)}")
    enum_lines.append("};")
    enum_lines.append("")

    hash_h = "\n".join([
        "#pragma once",
        "",
        f"/* {WARNING} */",
        "",
        f"#define PRG32_ABI_MAJOR {major}u",
        f"#define PRG32_ABI_MINOR {minor}u",
        f"#define PRG32_ABI_HASH 0x{hash_value:08x}u",
        "",
    ])

    table = [
        f"/* {WARNING} */",
        "",
        '#include "prg32.h"',
        '#include "prg32_abi.h"',
        "",
        "const prg32_abi_table_t prg32_abi_table = {",
        "    .magic = PRG32_ABI_MAGIC,",
        "    .abi_major = PRG32_ABI_MAJOR,",
        "    .abi_minor = PRG32_ABI_MINOR,",
        "    .struct_size = sizeof(prg32_abi_table_t),",
        "    .fn_count = PRG32_ABI_FN_COUNT,",
        "    .abi_hash = PRG32_ABI_HASH,",
        "    .provided_features = PRG32_FEATURE_AUDIO | PRG32_FEATURE_WIFI |",
        "                         PRG32_FEATURE_MULTIPLAYER | PRG32_FEATURE_METRICS |",
        "                         PRG32_FEATURE_AUDIO_PLUS | PRG32_FEATURE_KEYBOARD |",
        "                         PRG32_FEATURE_TILEMAP | PRG32_FEATURE_PLATFORMER |",
        "                         PRG32_FEATURE_SPRITES,",
        "    .functions = {",
    ]
    for fn in functions:
        table.append(f"        [{enum_name(fn['name'])}] = (const void *){fn['name']},")
    table.extend(["    },", "};", ""])

    py = [
        f"# {WARNING}",
        "",
        f"ABI_MAJOR = {major}",
        f"ABI_MINOR = {minor}",
        f"ABI_HASH = 0x{hash_value:08x}",
        "IMPORT_NAMES = [",
    ]
    for fn in functions:
        py.append(f"    {fn['name']!r},")
    py.extend(["]", ""])
    py.append("FEATURE_BITS = {")
    for key, macro in FEATURE_BITS.items():
        py.append(f"    {key!r}: {macro.replace('PRG32_FEATURE_', '1 << ') if False else feature_value(key)},")
    py.extend(["}", ""])

    return {
        ROOT / "components/prg32/include/prg32_abi_index.h": "\n".join(enum_lines),
        ROOT / "components/prg32/include/prg32_abi_hash.h": hash_h,
        ROOT / "components/prg32/prg32_abi_table.c": "\n".join(table),
        ROOT / "prg32/abi/abi_generated.py": "\n".join(py),
    }


def feature_value(name: str) -> int:
    order = [
        "audio",
        "wifi",
        "multiplayer",
        "metrics",
        "audio_plus",
        "keyboard",
        "tilemap",
        "platformer",
        "sprites",
    ]
    return 1 << order.index(name)


def abi_gen_cmd(args: argparse.Namespace) -> None:
    abi = load_abi(ABI_JSON)
    files = generated_files(abi)
    for path, content in files.items():
        content = content.rstrip() + "\n"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

def abi_check_cmd(args: argparse.Namespace) -> None:
    abi = load_abi(ABI_JSON)
    files = generated_files(abi)
    mismatches = []
    for path, content in files.items():
        content = content.rstrip() + "\n"
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            mismatches.append(path)
    if mismatches:
        for path in mismatches:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        raise SystemExit(1)
