#pragma once

/* Generated by prg32; do not edit manually. */

#define PRG32_ABI_MAJOR 1u
#define PRG32_ABI_MINOR 3u
#define PRG32_ABI_HASH 0x5626cb8au
#define PRG32_ABI_COMPAT_HASH_0 0xec21efe2u
#define PRG32_ABI_HASH_IS_COMPATIBLE(value) (((value) == PRG32_ABI_HASH) || ((value) == PRG32_ABI_COMPAT_HASH_0))
