#pragma once

/* Generated by prg32; do not edit manually. */

#define PRG32_ABI_MAJOR 1u
#define PRG32_ABI_MINOR 6u
#define PRG32_ABI_HASH 0x260f6136u
#define PRG32_ABI_COMPAT_HASH_0 0x006427c2u
#define PRG32_ABI_COMPAT_HASH_1 0x6be6e8d0u
#define PRG32_ABI_HASH_IS_COMPATIBLE(value) (((value) == PRG32_ABI_HASH) || ((value) == PRG32_ABI_COMPAT_HASH_0) || ((value) == PRG32_ABI_COMPAT_HASH_1))
