#pragma once

/* Generated by prg32; do not edit manually. */

#define PRG32_ABI_MAJOR 1u
#define PRG32_ABI_MINOR 5u
#define PRG32_ABI_HASH 0x6be6e8d0u
#define PRG32_ABI_HASH_IS_COMPATIBLE(value) (((value) == PRG32_ABI_HASH))
